[mb2] Create .mb2 directory after all checks are done
sailfishos/sdk-setup pull request #209
Opened 2020-11-07 15:50 UTC by Thaodan

When running mb2 with an invalid option or in a directory without a
yaml/spec file mb2 still creates a .mb2 directory and litters the file
system.

2020-11-09 05:43 UTC, vigejolla requested changes
There's no bug reference (JB#XXXXX) anywhere

2020-11-09 05:43 UTC, vigejolla commented on sdk-setup/src/mb2
Extra empty line left here

2020-11-09 07:15 UTC, martyone commented on sdk-setup/src/mb2
> +
This is too late. At least the switch_to_snapshot call above needs $STATEDIR.

2020-11-09 08:22 UTC, Thaodan commented
Moved the check further up before `switch_to_snapshot` might be used.

2020-11-09 08:37 UTC, martyone commented
Pity the effect is really limited now :\ I think you could set up an exit trap and remove the .mb2 dir on exit if it contains nothing else than the pre-created .gitignore file.

2020-11-09 08:50 UTC, Thaodan commented
It is fine as the options are valid at this point.

2020-11-09 09:03 UTC, martyone commented
The .spec has not been processed yet at this point, so running mb2 with correct options but under a random directory with no .spec will leave .mb2 dir there.

2020-11-14 06:11 UTC, Thaodan commented
I moved the processing of the spec file a bit further just before the 
switching to the snapshot now.

2020-11-18 06:18 UTC, martyone commented
That's not possible either. `run_undeploy__process_args` and `run_check__process_args` may set `OPT_NEEDSPEC`, which would happen after spec processing (look for `${cmd}__process_args` invocation). I think the only workable option is to use the exit trap as suggested before.

2020-12-08 23:46 UTC, Thaodan commented
``` emacs-lisp

(defun test)
```

2021-12-10 12:05 UTC, martyone commented
Superseded by #282

2021-12-10 12:05 UTC, closed without merging